### ISSUE TITLE
Job does not work

### ISSUE THREAD

**Issue by OwnerDevSoviet** [CylexVII/cylex_jobs#5]
Hello, I am using a dual job system AND kashacters on v1final. I am attempting to use the script but its constantly running errors. Ive fixed 4 errors yet theres more and more. Can this be looked into as the minute u check the box on require job it starts breaking.

My current issues iv noticed is 1. Config file needs called in fxmanifest under client and server
2. The tables arent registering once u fix this issue and write config = {} on the top of config.
3.  Once you do this you must change the Jobs in pairs to Config.Jobs, but then it breaks location. 
I added you on discord aswell as maybe youll have a simple trick for this but it is so far erroring a lot. Love the concept, but cant get it to work with required job

**Comment by CylexVII** [comment]
Fixed
