### ISSUE TITLE
canCarryItem Error when I Collect, Process or Packing

### ISSUE THREAD

**Issue by Christian21lp** [CylexVII/cylex_jobs#6]
Hello, I have a problem when I want to Collect, Process or Packing. I become a Error and i become Nothing in my Inventory: 

SCRIPT ERROR: @cylex_jobs/server/server.lua:40: attempt to call a nil value (field 'canCarryItem')

**Comment by Ruqen** [comment]
You must have weight system.

**Comment by CylexVII** [comment]
Script based on weight system. You can change canCarryItem to getInventoryItem(item).count

**Comment by CylexVII** [comment]
Fixed.
