### ISSUE TITLE
Cannot create a second job

### ISSUE THREAD

**Issue by OwnerDevSoviet** [CylexVII/cylex_jobs#7]
I create a second job, and it does not error, yet it does not show. Please post an update commented out config that we can base this off of or update the script to provide more support on this.I have tested 14 different tries and seems each doesnt work. There is 0 syntax errrors aswell
I will upload a link so u can see what is happening

https://pastebin.com/1CQCteDS
Thanks

**Comment by CylexVII** [comment]
https://pastebin.com/bsq20uTX
try this.

**Comment by OwnerDevSoviet** [comment]
No good.


https://user-images.githubusercontent.com/70889124/106525484-e8e41380-6498-11eb-9e08-e29af7b77bd4.mp4

**Comment by OwnerDevSoviet** [comment]
I added u on discord. Please add me back. SovietRulez

**Comment by OwnerDevSoviet** [comment]
```lua  if PlayerData.job2.name ~= v.jobName then
                                show = false
                                wait = 1
                            end``` This was the issue. I noticed the wait was 500, changed to 1 and works just fine

**Comment by OwnerDevSoviet** [comment]
```lua
 if PlayerData.job2.name ~= v.jobName then
                                show = false
                                wait = 500
                            end```
Noticed this was the issue.

Multiple jobs cannot have 500. U need to change it to
```lua
 if PlayerData.job2.name ~= v.jobName then
                                show = false
                                wait = 1
                            end```(could  do 0 but ill play with the value a bit)

**Comment by CylexVII** [comment]
Fixed on last commit
